### ISSUE TITLE
Suggest method seem to be broken with 5.0.0

### ISSUE THREAD

**Issue by francoism90** [sleimanx2/plastic#129]
```
 (1/1) BadRequest400Exception

{"error":{"root_cause":[{"type":"invalid_type_name_exception","reason":"Document mapping type name can't start with '_', found: [_suggest]"}],"type":"invalid_type_name_exception","reason":"Document mapping type name can't start with '_', found: [_suggest]"},"status":400}
```
Everything else works fine, and this worked before the upgrade.

Could you please tell me what may be wrong? :)

Thanks!

**Comment by mwleinad** [comment]
@sleimanx2 I'm getting the same :(

**Comment by overbost** [comment]
Is not a bug... but Plastic need to update to Elasticsearch changes

> _suggest endpoint has been deprecated in favour of using suggest via _search endpoint. In 5.0, the _search endpoint has been optimized for suggest only search requests.

There are a lot of issues cause the changes between Elasticsearch versions, like in 6.x only 1 type per index is allowed, and in 7.x will be removed the types. I spend 1 day to learn that, and the doc/wiki about Plastic don't explain it. I solve it editing the config and set the indexes model by model.

I suggest to add a config in Plastic, to set which version of Elasticsearch you want to use. If you know which version you want to use you can send the correct request in according to the Elasticsearch changes.

Otherwise the dev can create new branch, for example Plastic 6 for version 6.x, with correct queries.

Anyone fix this problem for now?
